### PR TITLE
WIP: allow kguess to specify MPB lattice vector

### PR DESCRIPTION
**Pull request by stevengj**
This PR implements the feature discussed in #612: in order to create a source for an oblique waveguide, it would be nice to be able to tell MPB that the waveguide direction is not perpendicular to the cross-section.

In this PR, that is done through the `kguess` parameter: if you specify a nonzero `kguess` *and* you specify a direction of `NO_DIRECTION` to the eigenmode source, then it takes the direction of the third lattice vector to be the `kguess` direction.

This should allow you to create an oblique mode source, but I haven't tested it yet so this should be considered a rough draft.  cc @oskooi

### CODE REVIEW

**Comment by oskooi** [comment]
From Travis, there are 5 failing tests in the Python suite (`python/tests`) all involving either the mode decomposition or the eigenmode source feature:

**binary_grating.py**
```
meep: zero-frequency bands at k=0 are ill-defined
```
**kdom.py**
```
CHECK failure on line 388 of eigensolver.c: crazy number detected in trace!!
```
**mode_coeffs.py**
```
meep: zero-frequency bands at k=0 are ill-defined
```
**mode_decomposition.py**
```
meep: zero-frequency bands at k=0 are ill-defined
```
**wvg_src.py**
```
meep: zero-frequency bands at k=0 are ill-defined
```
I was able to reproduce these test failures on my local machine as well. Once we can get these tests to pass, I can proceed with additional testing.

**Comment by oskooi** [comment]
This feature doesn't seem to be working correctly as demonstrated by the following test which involves computing the flux of the fundamental mode of a linear waveguide with its axis rotated. An eigenmode source is used with its `eig_kpoint` parameter set to the waveguide axis. Note that there is no `kguess` parameter. Setting `direction=mp.NO_DIRECTION` produces an error: `CHECK failure on line 388 of eigensolver.c: crazy number detected in trace!!` and thus `direction=mp.AUTOMATIC` had to be used.

```py
import meep as mp
import math

cell_size = mp.Vector3(10,10,0)

pml_layers = [mp.PML(thickness=1.0)]

rot_angle = math.radians(40)  # rotation angle of waveguide, CCW around z-axis                                                                                                           

sources = [mp.EigenModeSource(src=mp.GaussianSource(1.0,fwidth=0.1),
                              size=mp.Vector3(y=10),
                              center=mp.Vector3(x=-3),
                              direction=mp.AUTOMATIC,
                              eig_kpoint=mp.Vector3(math.cos(rot_angle),math.sin(rot_angle),0),
                              eig_band=1,
                              eig_parity=mp.ODD_Z,
                              eig_match_freq=True)]

geometry = [mp.Block(center=mp.Vector3(),
                     size=mp.Vector3(mp.inf,1,mp.inf),
                     e1 = mp.Vector3(1,0,0).rotate(mp.Vector3(0,0,1), rot_angle),
                     e2 = mp.Vector3(0,1,0).rotate(mp.Vector3(0,0,1), rot_angle),
                     material=mp.Medium(index=1.5))]

sim = mp.Simulation(cell_size=cell_size,
                    resolution=50,
                    boundary_layers=pml_layers,
                    sources=sources,
                    geometry=geometry)

tran = sim.add_flux(1.0, 0, 1, mp.FluxRegion(center=mp.Vector3(x=4).rotate(mp.Vector3(z=1),rot_angle), size=mp.Vector3(y=3.0)))

sim.run(until_after_sources=100)
print("flux:, {:.2f}, {:.6f}".format(math.degrees(rot_angle),mp.get_fluxes(tran)[0]))
```

The flux values for three different waveguide orientations &mdash; 0°, 20°, and 40° &mdash; specified by the `rot_angle` parameter are:

```
flux:, 0.00, 16.410616
flux:, 20.00, 16.306702
flux:, 40.00, 13.334872
```

A snapshot of the mode profile for the three waveguide orientations also demonstrates that the eigenmode source is not correctly exciting the fundamental mode.

waveguide_eigenmodesrc

I suspect that unless `direction=mp.NO_DIRECTION` can be used, as originally described so that MPB knows exactly which wavevector to use, this feature itself cannot be used properly.

**Comment by stevengj** [comment]
You might want to put in some more printfs to make sure the lattice vectors (R), reciprocal lattice vectors (G), and k are correct.

**Comment by oskooi** [comment]
```
sim.run(mp.at_beginning(mp.output_epsilon), mp.at_every(5.3, mp.output_efield_z), until_after_sources=0)
```

**Comment by stevengj** [comment]
Looking good now:
image

**Comment by oskooi** [comment]
It seems that everything is now working correctly. The following is a test (`waveguide_flux.py`) that can be added to the `python/tests` suite which is based on the previous example of computing the flux in a linear waveguide having three different rotation orientations.

```py
from __future__ import division

import meep as mp
import math
import unittest

class TestEigenmodeSource(unittest.TestCase):

    def test_waveguide_flux(self):
        cell_size = mp.Vector3(10,10,0)

        pml_layers = [mp.PML(thickness=2.0)]

        rot_angles = range(0,60,20) # rotation angle of waveguide, CCW around z-axis                                                                                     

        fluxes = []
        for t in rot_angles:
            rot_angle = math.radians(t)
            sources = [mp.EigenModeSource(src=mp.GaussianSource(1.0,fwidth=0.1),
                                          size=mp.Vector3(y=10),
                                          center=mp.Vector3(x=-3),
                                          direction=mp.NO_DIRECTION,
                                          eig_kpoint=mp.Vector3(math.cos(rot_angle),math.sin(rot_angle),0),
                                          eig_band=1,
                                          eig_parity=mp.ODD_Z,
                                          eig_match_freq=True)]

            geometry = [mp.Block(center=mp.Vector3(),
                                 size=mp.Vector3(mp.inf,1,mp.inf),
                                 e1 = mp.Vector3(1,0,0).rotate(mp.Vector3(0,0,1), rot_angle),
                                 e2 = mp.Vector3(0,1,0).rotate(mp.Vector3(0,0,1), rot_angle),
                                 material=mp.Medium(index=1.5))]

            sim = mp.Simulation(cell_size=cell_size,
                                resolution=50,
                                boundary_layers=pml_layers,
                                sources=sources,
                                geometry=geometry)

            tran = sim.add_flux(1.0, 0, 1, mp.FluxRegion(center=mp.Vector3(x=3), size=mp.Vector3(y=10)))

            sim.run(until_after_sources=100)

            fluxes.append(mp.get_fluxes(tran)[0])
            print("flux:, {:.2f}, {:.6f}".format(t,fluxes[-1]))

        self.assertAlmostEqual(fluxes[0], fluxes[1], places=0)
        self.assertAlmostEqual(fluxes[1], fluxes[2], places=0)
        self.assertAlmostEqual(fluxes[0], fluxes[2], places=0)

if __name__ == '__main__':
    unittest.main()
```
The test verifies that the flux values for the three cases are nearly equivalent. This is because it seems that the flux values for the three cases all converge to the same value with increasing resolution (i.e., there is no normalization factor in the source that needs to be separately accounted for).
```
resolution=50

flux:, 0.00, 16.410934
flux:, 20.00, 16.390350
flux:, 40.00, 16.324424

resolution=70

flux:, 0.00, 16.383468
flux:, 20.00, 16.372891
flux:, 40.00, 16.332205

resolution=90

flux:, 0.00, 16.372234
flux:, 20.00, 16.365782
flux:, 40.00, 16.335413
```

**Pull request merged**
