### PR TITLE
tutorial example for Mie scattering of a lossless sphere

### PR DESCRIPTION
**Pull request by oskooi**
There have been a couple of requests for this recently in the [mailing list](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg06415.html) as well as #980, #1040, etc.

A Scheme version and Jupyter notebooks will be added in a separate PR.

### CODE REVIEW

**Comment by stevengj** [comment]
Note that the scattering cross section is different from the [radar cross section](https://en.wikipedia.org/wiki/Radar_cross-section#Definition).

The scattering cross section is (total scattered power in all directions) / (incident intensity).

To compute the RCS in a given direction (e.g. backscattered), the simplest method is probably to use the near2far feature to get the fields, and hence the Poynting flux `F = r̂⋅Re[E*×H]/2` (= intensity in the outward direction), at a large distance R >> (object diameter).     Then, if I understand the definition correctly, the RCS σ in that direction is `σ = 4πR²F / (incident intensity)`.

**Comment by stevengj** [comment]
Note that you should be plotting a dimensionless quantity: cross section / sphere area, not power / area.   To get the scattering cross section, as mentioned above, just divide the power by the incident intensity.

To get the incident intensity, the simplest thing would be to compute the flux (power) in one of the flux planes from your normalization run and divide it by the area of that flux plane.

**Comment by senselessDev** [comment]
Why are we simulating everything over and over again, just changing the radius of the sphere? Because we are interested in the quantity circumference/wavelength, it should be correct to simulate with a constant radius but use a wide bandwidth, no?

In openEMS it is also done with a fixed radius, as you can see [here](https://github.com/thliebig/openEMS/blob/master/python/Tutorials/RCS_Sphere.py).

**Comment by senselessDev** [comment]
mie_scattering

After having the script running for the last 4 hours on my machine, I got the result above. I'm surprised, that it is substantially different from your one. 

conda pymeep version: `pymeep                    1.10.0          mpi_mpich_py37h352eada_7    conda-forge`

which is by the way different from the version reported in python:
```Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import meep
Using MPI version 3.1, 1 processes

In [2]: meep.__version__
Out[2]: '1.8.0-106-ga4915888'
```

**Comment by oskooi** [comment]
Indeed, rather than computing the scattering cross section via separate simulations for different values of the sphere radius, we can do just one broadband simulation with a fixed radius (as shown below). Might be worthwhile to demonstrate that both approaches produce the same result although one is more computationally efficient. 

However, the bug reported in #1046 needs to be resolved first. 

```py
import meep as mp
import numpy as np
import matplotlib.pyplot as plt

resolution = 20

r = 0.5  # radius of sphere

wvl_min = 2*np.pi*r/10
wvl_max = 2*np.pi*r/0.1

fmin = 1/wvl_max
fmax = 1/wvl_min
fcen = 0.5*(fmin+fmax)
df = fmax-fmin
nfreq = 100

dpml = wvl_max
dair = 0.5*wvl_max

pml_layers = [mp.PML(thickness=dpml)]

symmetries = [mp.Mirror(mp.Y),
              mp.Mirror(mp.Z,phase=-1)]

s = 2*(dpml+dair+r)
cell_size = mp.Vector3(s,s,s)

sources = [mp.Source(mp.GaussianSource(fcen,fwidth=df),
                     center=mp.Vector3(-0.5*s+dpml),
                     size=mp.Vector3(0,s,s),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),
                    symmetries=symmetries)

input = sim.add_flux(fcen, df, nfreq,
                     mp.FluxRegion(center=mp.Vector3(0.5*s-dpml),size=mp.Vector3(0,s-2*dpml,s-2*dpml)))

box = sim.add_flux(fcen, df, nfreq,
                   mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r,2*r),weight=+1),
                   mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r,2*r),weight=-1),
                   mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0,2*r),weight=+1),
                   mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0,2*r),weight=-1),
                   mp.FluxRegion(center=mp.Vector3(z=-r),size=mp.Vector3(2*r,2*r,0),weight=+1),
                   mp.FluxRegion(center=mp.Vector3(z=+r),size=mp.Vector3(2*r,2*r,0),weight=-1))

sim.run(until_after_sources=20)

input_flux = mp.get_fluxes(input)
freqs = mp.get_flux_freqs(input)
box_flux_data = sim.get_flux_data(box)
box_flux = mp.get_fluxes(box)

sim.reset_meep()

geometry = [mp.Sphere(material=mp.metal,
                      center=mp.Vector3(),
                      radius=r)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),
                    symmetries=symmetries,
                    geometry=geometry)

box = sim.add_flux(fcen, df, nfreq,
                   mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r,2*r),weight=+1),
                   mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r,2*r),weight=-1),
                   mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0,2*r),weight=+1),
                   mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0,2*r),weight=-1),
                   mp.FluxRegion(center=mp.Vector3(z=-r),size=mp.Vector3(2*r,2*r,0),weight=+1),
                   mp.FluxRegion(center=mp.Vector3(z=+r),size=mp.Vector3(2*r,2*r,0),weight=-1))

sim.load_minus_flux_data(box, box_flux_data)

sim.run(until_after_sources=40)

scat_flux = mp.get_fluxes(box)

if mp.am_master():
    plt.figure(dpi=150)
    plt.loglog(2*np.pi*r*freqs,np.divide(scat_flux,input_flux)*1/(np.pi*r**2),'bo-')
    plt.grid(True,which="both",ls="-")
    plt.xlabel('(sphere circumference)/wavelength, 2πr/λ')
    plt.ylabel(r'(scattered cross section)/(sphere cross area), $\sigma$/(πr$^{2}$)')
    plt.title('Mie scattering of a lossless metallic sphere')
    plt.show()
```

**Comment by oskooi** [comment]
Following the fix described in #1046 of adding `is_integrated=True` to the source in order to generate a planewave in the PML region, the following script produces results which are qualitatively closer to the [analytic Mie theory](http://www.rfcafe.com/references/electrical/ew-radar-handbook/images/imgp8C.gif) than previous results without the fix. However, as can be seen in the accompanying plot, the dimensionless ratio of scattering cross section to the cross sectional area seems to be converging to a value between 2 and 3 rather than 1 as predicted by the theory. This discrepancy is likely due to the normalization of two of the terms: (1) incident intensity=flux/(area of flux plane) and (2) cross sectional area of a sphere. Replacing the area of the flux plane (2r)<sup>2</sup> with e.g. half the surface area of the sphere (2πr<sup>2</sup>) and the cross sectional area of a sphere (πr<sup>2</sup>) with the total surface area of the sphere (4πr<sup>2</sup>) did not produce the expected results. Perhaps something else is being overlooked?

```py
import meep as mp
import numpy as np
import matplotlib.pyplot as plt

resolution = 25 # at least 8 pixels per smallest wavelength

r = 0.5  # radius of sphere                                                                                                                                             

wvl_min = 2*np.pi*r/10
wvl_max = 2*np.pi*r/0.5

frq_min = 1/wvl_max
frq_max = 1/wvl_min
frq_cen = 0.5*(frq_min+frq_max)
dfrq = frq_max-frq_min
nfrq = 100

dpml = 0.5*wvl_max
dair = 0.5*wvl_max

pml_layers = [mp.PML(thickness=dpml)]

symmetries = [mp.Mirror(mp.Y),
              mp.Mirror(mp.Z,phase=-1)]

s = 2*(dpml+dair+r)
cell_size = mp.Vector3(s,s,s)

sources = [mp.Source(mp.GaussianSource(frq_cen,fwidth=dfrq,is_integrated=True),
                     center=mp.Vector3(-0.5*s+dpml),
                     size=mp.Vector3(0,s-2*dpml,s-2*dpml),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=resolution,
                    eps_averaging=False,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),
                    symmetries=symmetries)

box_xp = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r,2*r)))
box_xm = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r,2*r)))
box_yp = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0,2*r)))
box_ym = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0,2*r)))
box_zp = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=-r),size=mp.Vector3(2*r,2*r,0)))
box_zm = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=+r),size=mp.Vector3(2*r,2*r,0)))

sim.run(until_after_sources=20)

freqs = mp.get_flux_freqs(box_xp)
box_xp_data = sim.get_flux_data(box_xp)
box_xm_data = sim.get_flux_data(box_xm)
box_yp_data = sim.get_flux_data(box_yp)
box_ym_data = sim.get_flux_data(box_ym)
box_zp_data = sim.get_flux_data(box_zp)
box_zm_data = sim.get_flux_data(box_zm)

box_xp_flux0 = mp.get_fluxes(box_xp)
box_xm_flux0 = mp.get_fluxes(box_xm)
box_yp_flux0 = mp.get_fluxes(box_yp)
box_ym_flux0 = mp.get_fluxes(box_ym)
box_zp_flux0 = mp.get_fluxes(box_zp)
box_zm_flux0 = mp.get_fluxes(box_zm)

sim.reset_meep()

geometry = [mp.Sphere(material=mp.metal,
                      center=mp.Vector3(),
                      radius=r)]

sim = mp.Simulation(resolution=resolution,
                    eps_averaging=False,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),
                    symmetries=symmetries,
                    geometry=geometry)

box_xp = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r,2*r)))
box_xm = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r,2*r)))
box_yp = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0,2*r)))
box_ym = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0,2*r)))
box_zp = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=-r),size=mp.Vector3(2*r,2*r,0)))
box_zm = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=+r),size=mp.Vector3(2*r,2*r,0)))

sim.load_minus_flux_data(box_xp, box_xp_data)
sim.load_minus_flux_data(box_xm, box_xm_data)
sim.load_minus_flux_data(box_yp, box_yp_data)
sim.load_minus_flux_data(box_ym, box_ym_data)
sim.load_minus_flux_data(box_zp, box_zp_data)
sim.load_minus_flux_data(box_zm, box_zm_data)

sim.run(until_after_sources=50)

box_xp_flux = mp.get_fluxes(box_xp)
box_xm_flux = mp.get_fluxes(box_xm)
box_yp_flux = mp.get_fluxes(box_yp)
box_ym_flux = mp.get_fluxes(box_ym)
box_zp_flux = mp.get_fluxes(box_zp)
box_zm_flux = mp.get_fluxes(box_zm)

scatt_flux = np.asarray(box_xp_flux)-np.asarray(box_xm_flux)+np.asarray(box_yp_flux)-np.asarray(box_ym_flux)+np.asarray(box_zp_flux)-np.asarray(box_zm_flux)
intensity = np.asarray(box_xp_flux0)/(2*r)**2
scatt_cross_section = np.divide(scatt_flux,intensity)

if mp.am_master():
    plt.figure(dpi=150)
    plt.loglog(2*np.pi*r*np.asarray(freqs),scatt_cross_section*-1/(np.pi*r**2),'bo-')
    plt.grid(True,which="both",ls="-")
    plt.xlabel('(sphere circumference)/wavelength, 2πr/λ')
    plt.ylabel(r'(scattered cross section)/(sphere cross area), $\sigma$/(πr$^{2}$)')
    plt.title('Mie scattering of a lossless metallic sphere')
    plt.savefig("scatt_cross_section_res{}.png".format(resolution))
```

(note: this is a 3d simulation which runs in about 20 minutes on an 8 core Intel Xeon 2.9 GHz machine)

foo

Also, there is an additional anomaly. For the normalization run involving a planewave propagating in the *+x* direction in the empty cell, the flux through the two *x* monitors should be identical but they are not. This is shown in the figure below where the flux spectrum of the two monitors is slightly offset. For comparison, the flux in the two *y* and two *z* monitors of the six-sided box *are* identical.

foo2

One possibility is that the wavefronts are *not* exactly planar. Perhaps this is caused by artifacts of the fields in the PML region. Non-planar wavefronts will obviously affect the accuracy of the results.

**Comment by senselessDev** [comment]
Just for fun, I simulated it for different resolutions:

mie_meep

Is it expected to see this kind of a difference? It is not much, but more than what I would have thought. Probably connected to the non-perfect planarity still..

**Comment by oskooi** [comment]
There was a bug in the script posted [above](https://github.com/NanoComp/meep/pull/1045#issuecomment-550573337): in the `source` definition, instead of `size=mp.Vector3(0,s-2*dpml,s-2*dpml)`, it should have been `size=mp.Vector3(0,s,s)`. This way, the source extends all the way into the PML to the cell edge and thus is a true "infinitely"-extended source which generates planar wavefronts. Any finite-length source generates non-planar wavefronts which was why there was a discrepancy in the flux spectra shown above. With the corrected source, the flux spectra from the two monitors in an empty cell are  identical as shown below.

foo2

The strong resolution-dependence of the results is due to the lossless metallic sphere which introduces discretization/staircasing artifacts along its surface since Meep's [subpixel smoothing](https://meep.readthedocs.io/en/latest/Subpixel_Smoothing/) can only be applied to lossless, wavelength-independent *dielectric* materials (i.e. purely real index of refraction). Subpixel smoothing does not work with lossless metals. Thus, there is no recourse in this situation but to use a large `resolution` to ensure that the results are sufficiently accurate. This is where things become challenging: the computational resource requirements become exorbitant. As a comparison, the scattering cross section spectra is shown below for `resolution` values of `25`, `40`, and `50`. Note that at large frequencies (i.e. small wavelengths) where the discretization effects are most pronounced, the results are gradually converging to those of the analytic theory (i.e. "flattening" out to a constant value). The challenge for 3d simulations though is that doubling the `resolution` multiplies the storage requirements by a factor of eight and the number of timesteps by a factor of two; these are intrinsic constraints of the [Yee grid](https://meep.readthedocs.io/en/latest/Yee_Lattice/). The `resolution=25` case took `254.9` s,  `resolution=40` took `1573.9` s, and `resolution=50` took `3588.3` s. Doubling the `resolution` resulted in the runtime to increase by a factor of 14. Perhaps it would be more convenient to demonstrate Mie scattering for a 2d geometry (e.g., cylinder)? This would make for a much smaller and quicker simulation.

foo1


(note: at large frequencies, the dimensionless ratio is still converging to a value between 2 and 3 rather 1 which needs to be corrected.)

**Comment by stevengj** [comment]
Actually, if I remember correctly, the scattering cross section divided by the cross sectional area should converge to 2, not 1.   (The factor of 2 comes from the forward scattering required to give the "shadow" by cancelling the incident field.)

**Comment by stevengj** [comment]
For reference, see also http://homerreid.github.io/scuff-em-documentation/examples/MieScattering/MieScattering/

**Comment by xj361685640** [comment]
I think it is necessary to compare with Mie series.

**Comment by oskooi** [comment]
Replacing the metallic sphere with a dielectric one (in order to improve accuracy at low resolutions as well as speed up the calculation) and comparing the results to the analytic Mie theory via [PyMieScatt](https://pymiescatt.readthedocs.io/en/latest/) shows good agreement:

mie_scattering

```py
import meep as mp
import numpy as np
import matplotlib.pyplot as plt
import PyMieScatt as ps

r = 1.0  # radius of sphere

wvl_min = 2*np.pi*r/10
wvl_max = 2*np.pi*r/2

frq_min = 1/wvl_max
frq_max = 1/wvl_min
frq_cen = 0.5*(frq_min+frq_max)
dfrq = frq_max-frq_min
nfrq = 100

## at least 8 pixels per smallest wavelength, i.e. np.floor(8/wvl_min)
resolution = 30

dpml = 0.5*wvl_max
dair = 0.5*wvl_max

pml_layers = [mp.PML(thickness=dpml)]

symmetries = [mp.Mirror(mp.Y),
              mp.Mirror(mp.Z,phase=-1)]

s = 2*(dpml+dair+r)
cell_size = mp.Vector3(s,s,s)

# is_integrated=True necessary for any planewave source extending into PML
sources = [mp.Source(mp.GaussianSource(frq_cen,fwidth=dfrq,is_integrated=True),
                     center=mp.Vector3(-0.5*s+dpml),
                     size=mp.Vector3(0,s,s),
                     component=mp.Ez)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),
                    symmetries=symmetries)

box_x1 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r,2*r)))
box_x2 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r,2*r)))
box_y1 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0,2*r)))
box_y2 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0,2*r)))
box_z1 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=-r),size=mp.Vector3(2*r,2*r,0)))
box_z2 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=+r),size=mp.Vector3(2*r,2*r,0)))

sim.run(until_after_sources=20)

freqs = mp.get_flux_freqs(box_x1)
box_x1_data = sim.get_flux_data(box_x1)
box_x2_data = sim.get_flux_data(box_x2)
box_y1_data = sim.get_flux_data(box_y1)
box_y2_data = sim.get_flux_data(box_y2)
box_z1_data = sim.get_flux_data(box_z1)
box_z2_data = sim.get_flux_data(box_z2)

box_x1_flux0 = mp.get_fluxes(box_x1)
box_x2_flux0 = mp.get_fluxes(box_x2)
box_y1_flux0 = mp.get_fluxes(box_y1)
box_y2_flux0 = mp.get_fluxes(box_y2)
box_z1_flux0 = mp.get_fluxes(box_z1)
box_z2_flux0 = mp.get_fluxes(box_z2)

sim.reset_meep()

n_sphere = 2.0
geometry = [mp.Sphere(material=mp.Medium(index=n_sphere),
                      center=mp.Vector3(),
                      radius=r)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=mp.Vector3(),
                    symmetries=symmetries,
                    geometry=geometry)

box_x1 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=-r),size=mp.Vector3(0,2*r,2*r)))
box_x2 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(x=+r),size=mp.Vector3(0,2*r,2*r)))
box_y1 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(y=-r),size=mp.Vector3(2*r,0,2*r)))
box_y2 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(y=+r),size=mp.Vector3(2*r,0,2*r)))
box_z1 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=-r),size=mp.Vector3(2*r,2*r,0)))
box_z2 = sim.add_flux(frq_cen, dfrq, nfrq, mp.FluxRegion(center=mp.Vector3(z=+r),size=mp.Vector3(2*r,2*r,0)))

sim.load_minus_flux_data(box_x1, box_x1_data)
sim.load_minus_flux_data(box_x2, box_x2_data)
sim.load_minus_flux_data(box_y1, box_y1_data)
sim.load_minus_flux_data(box_y2, box_y2_data)
sim.load_minus_flux_data(box_z1, box_z1_data)
sim.load_minus_flux_data(box_z2, box_z2_data)

sim.run(until_after_sources=60)

box_x1_flux = mp.get_fluxes(box_x1)
box_x2_flux = mp.get_fluxes(box_x2)
box_y1_flux = mp.get_fluxes(box_y1)
box_y2_flux = mp.get_fluxes(box_y2)
box_z1_flux = mp.get_fluxes(box_z1)
box_z2_flux = mp.get_fluxes(box_z2)

scatt_flux = np.asarray(box_x1_flux)-np.asarray(box_x2_flux)+np.asarray(box_y1_flux)-np.asarray(box_y2_flux)+np.asarray(box_z1_flux)-np.asarray(box_z2_flux)
intensity = np.asarray(box_x1_flux0)/(2*r)**2
scatt_cross_section = np.divide(scatt_flux,intensity)
scatt_eff_meep = scatt_cross_section*-1/(np.pi*r**2)
scatt_eff_theory = [ ps.MieQ(n_sphere,1000/f,2*r*1000,asDict=True)['Qsca'] for f in freqs ]

if mp.am_master():
    plt.figure(dpi=150)
    plt.loglog(2*np.pi*r*np.asarray(freqs),scatt_eff_meep,'bo-',label='Meep')
    plt.loglog(2*np.pi*r*np.asarray(freqs),scatt_eff_theory,'ro-',label='theory')
    plt.grid(True,which="both",ls="-")
    plt.xlabel('(sphere circumference)/wavelength, 2πr/λ')
    plt.ylabel('scattering efficiency, σ/πr$^{2}$)')
    plt.legend(loc='upper right')
    plt.title('Mie scattering of a lossless dielectirc sphere')
    plt.tight_layout()
    plt.savefig("mie_scattering.png")
```

**Comment by oskooi** [comment]
From the PyMieScatt analytic solver, in the limit of large frequencies (λ=2πr/100), the scattering efficiency oscillates around 2.0.

```py
import matplotlib.pyplot as plt
import PyMieScatt as ps
import numpy as np

r = 1.0 ## units of um

wvl_min = 2*np.pi*r/100
wvl_max = 2*np.pi*r/1
frq_min = 1/wvl_max
frq_max = 1/wvl_min
frqs = np.linspace(frq_min,frq_max,100)

## definition of scattering efficiency: http://www.thermopedia.com/content/956/
scatt = [ps.MieQ(2.0,1000/frq,2*r*1000,asDict=True)['Qsca'] for frq in frqs]

plt.figure(dpi=150)
plt.loglog(2*np.pi*r*np.asarray(frqs),scatt,'ro-')
plt.grid(True,which="both",ls="-")
plt.xlabel('(sphere circumference)/wavelength, 2πr/λ')
plt.ylabel('scattering efficiency, σ/πr$^{2}$)')
plt.show()
```

theory_frq

**Pull request merged**
