### PR TITLE
Fix images in MPB data analysis tutorial

### LINKED ISSUE #694: mpb_data_analysis.py produces incorrect images
I'll run `git bisect` to see when this was introduced.

### PR DESCRIPTION
**Pull request by ChristopherHogan**
Fixes #694. I'm not sure exactly what happened here, but #644 broke `mpb_data_analysis.py`.  It looks like one `ms` import was overwriting the other somehow. Importing them in separate functions fixes it.
@stevengj @oskooi

### CODE REVIEW

**Comment by JohnWeiner** [comment]
Hi Chris,

I visited your links to the various Github page in your previous message (pull request, file changes, and patch links).  Is there some way that I can replace my existing mpb_data_analysis.py with the revised version that should now work?  In other words is there somewhere on GitHub that I can download the fixed file or clone it?  Or does it just get incorporated into an overall revised version of MPB?

Best regards,

John

**Comment by JohnWeiner** [comment]
Hi again Chris,

A propos of this fix, you might be interested to know that even if all the code related to importing the diamond structure is commented out in mpb_data_analysis.py:

***********************************************************************************
# Import the ModeSolver from the mpb_tri_rods.py example
from mpb_tri_rods import ms as tr_ms
#from mpb_diamond import ms as d_ms


def tri_rods():
    efields = []

    # Band function to collect the efields
    def get_efields(tr_ms, band):
        efields.append(tr_ms.get_efield(band))

    tr_ms.run_tm(mpb.output_at_kpoint(mp.Vector3(1 / -3, 1 / 3), mpb.fix_efield_phase,
                                      get_efields))

    # Create an MPBData instance to transform the efields
    md = mpb.MPBData(rectify=True, resolution=32, periods=3)

    converted = []
    for f in efields:
        # Get just the z component of the efields
        f = f[..., 0, 2]
        converted.append(md.convert(f))

    tr_ms.run_te()

    eps = tr_ms.get_epsilon()
    plt.imshow(eps.T, interpolation='spline36', cmap='binary')
    plt.axis('off')
    plt.show()

    md = mpb.MPBData(rectify=True, resolution=32, periods=3)
    rectangular_data = md.convert(eps)
    plt.imshow(rectangular_data.T, interpolation='spline36', cmap='binary')
    plt.axis('off')
    plt.show()

    for i, f in enumerate(converted):
        plt.subplot(331 + i)
        plt.contour(rectangular_data.T, cmap='binary')
        plt.imshow(np.real(f).T, interpolation='spline36', cmap='RdBu', alpha=0.9)
        plt.axis('off')

    plt.show()


#def diamond():
 #   dpwr = []

#    def get_dpwr(ms, band):
 #       dpwr.append(ms.get_dpwr(band))

#    d_ms.run(mpb.output_at_kpoint(mp.Vector3(0, 0.625, 0.375), get_dpwr))

#    md = mpb.MPBData(rectify=True, periods=2, resolution=32)
#    converted_dpwr = [md.convert(d) for d in dpwr]

    # TODO: Plot


if __name__ == '__main__':
    tri_rods()
#    diamond()

********************************************************************************************************
If I run:

python mpb_data_analysi.py

I get a segmentation fault at the point where the solver is invoked:

(mp) johnweiner@johns-imac-pro-paris:~/pymeep/my_tutorials$ python mpb_data_analysis.py
Initializing eigensolver data
Computing 8 bands with 1e-07 tolerance
Working in 2 dimensions.
Grid size is 32 x 32 x 1.
Solving for 8 bands at a time.
Creating Maxwell data...
Mesh size is 3.
Lattice vectors:
     (0.866025, 0.5, 0)
     (0.866025, -0.5, 0)
     (0, 0, 1)
Cell volume = 0.866025
Reciprocal lattice vectors (/ 2 pi):
     (0.57735, 1, -0)
     (0.57735, -1, 0)
     (-0, 0, 1)
Geometric objects:
     cylinder, center = (0,0,0)
          radius 0.2, height 1e+20, axis (0, 0, 1)
Geometric object tree has depth 1 and 1 object nodes (vs. 1 actual objects)
Initializing epsilon function...
Allocating fields...
Solving for band polarization: tm.
Initializing fields to random numbers...
16 k-points
  Vector3<0.0, 0.0, 0.0>
  Vector3<0.0, 0.1, 0.0>
  Vector3<0.0, 0.2, 0.0>
  Vector3<0.0, 0.30000000000000004, 0.0>
  Vector3<0.0, 0.4, 0.0>
  Vector3<0.0, 0.5, 0.0>
  Vector3<-0.06666666666666667, 0.4666666666666667, 0.0>
  Vector3<-0.13333333333333333, 0.43333333333333335, 0.0>
  Vector3<-0.2, 0.39999999999999997, 0.0>
  Vector3<-0.26666666666666666, 0.36666666666666664, 0.0>
  Vector3<-0.3333333333333333, 0.3333333333333333, 0.0>
  Vector3<-0.26666666666666666, 0.26666666666666666, 0.0>
  Vector3<-0.19999999999999998, 0.19999999999999998, 0.0>
  Vector3<-0.1333333333333333, 0.1333333333333333, 0.0>
  Vector3<-0.06666666666666665, 0.06666666666666665, 0.0>
  Vector3<0.0, 0.0, 0.0>
elapsed time for initialization: 0.0019359588623046875
solve_kpoint (0,0,0):
tmfreqs:, k index, k1, k2, k3, kmag/2pi, tm band 1, tm band 2, tm band 3, tm band 4, tm band 5, tm band 6, tm band 7, tm band 8
Solving for bands 2 to 8...
Segmentation fault: 11

I am running this on an iMac, but I doubt if that is relevant.

Best regards,

John

**Comment by ChristopherHogan** [comment]
> Is there some way that I can replace my existing mpb_data_analysis.py with the revised version that should now work?

In general, once a PR is merged into the master branch the change will trigger a rebuild of the [nightly conda package](https://meep.readthedocs.io/en/latest/Installation/#nightly-builds), which should be on the `dev` label of the `chogan` channel and available for install within 24 ours of the merge. 

Alternatively, if you want to experiment before the PR is merged, you can check out the PR branch and build from source.

**Comment by ChristopherHogan** [comment]
@JohnWeiner, did you build from source or install a conda package? Can you run the following command to show the pymeep version?
```sh
$ python -c 'import meep; print(meep.__version__)'
```
It should work with the latest master branch.

**Comment by JohnWeiner** [comment]
Sorry for the last premature “send mail”…

I installed the conda package, but I haven’t tried with the nightly build.

The present conda-installed version, using the command line below, is

1.6.0-35-g3621a79b

John

**Comment by ChristopherHogan** [comment]
Yes, that's a bit outdated. You can try updating the pymeep package like this

```sh
$ conda update -c chogan/label/dev -c chogan -c conda-forge pymeep # or pymeep-parallel
```
However, I've found that `conda update` can often break an environment so I usually prefer to create a new environment (since they're cheap), keeping the old one in case you need to roll back.
```sh
$ conda create -n mp1.7 -c chogan/label/dev -c chogan -c conda-forge pymeep
$ conda activate mp1.7
```

**Comment by JohnWeiner** [comment]
OK thanks Chris…will do.

John

**Comment by JohnWeiner** [comment]
For activating the environment for the nightly builds (once created), is the command “conda activate mp_test” and “conda activate pmp_test”?

**Comment by ChristopherHogan** [comment]
The general command is
```sh
$ conda activate <environment name>
```
The name of the environment is whatever you pass to the `-n` flag in the `conda create` command. I think the meep docs still say
```sh
$ souce activate <environment name>
```
which accomplishes the same thing, but `source activate` is deprecated and `conda activate` is now preferred.

**Comment by JohnWeiner** [comment]
OK, thanks

**Comment by ChristopherHogan** [comment]
Is that after commenting out the `from mpb_diamond import ms as d_ms` and `diamond()` lines (since this fix isn't applied yet to the nightly builds)?

**Comment by JohnWeiner** [comment]
No, I didn’t touch anything…just ran the mpb_data_analysis.py script as is from the examples directory in the mp1.7 environment.  Ditto for the nightly build.  So the import command for both tri_rods and diamond should be there.

**Comment by ChristopherHogan** [comment]
I can reproduce this. MPB seems to be linking with a system `libBLAS.dylib` instead of the conda installed `libopenblas.dylib`, even though `otool -L` reports that `libmpb.dylib` is linked with `libopenblas.dylib`.

**Comment by JohnWeiner** [comment]
I just activated the mp1.7 environment on a pc box I have that is running Ubuntu Linux.  I tried the same thing as on the iMac, running python ./…../examples/mpb_data_analysis.py.  It DOES run on the pc box, and generates figures, but the “corrected” lattice does not look like round holes and the array of Ez fields superimposed on the lattice contour gives very strange looking results.  However it does not throw the segmentation fault.

**Comment by ChristopherHogan** [comment]
Right, that behavior is what this PR fixes. If you move the imports to their respective functions (the changes in this PR) you will see the correct images.

**Comment by JohnWeiner** [comment]
Chris you just lost me in the dust…

 If you move the imports to their respective functions (the changes in this PR) you will see the correct images.

I’m not quite sure what to do to make that happen.

**Comment by ChristopherHogan** [comment]
This conversation is happening in a thread for a pull request, the diff of which is at https://github.com/NanoComp/meep/pull/695/files. Those changes fixes the issue you see on Linux.

**Comment by ChristopherHogan** [comment]
The Mac issue is different though. It has to do with the way the conda packages are built. I'm investigating that now.

**Comment by JohnWeiner** [comment]
I just hand-typed your modifications in your PR into the mpb_data_analysis.py file on the PC box.  Then ran the script again and it works perfectly!

Is there a better way to incorporate the PR into the py file?  There must be something more intelligent than hand copying and typing!

John

**Comment by ChristopherHogan** [comment]
> Is there a better way to incorporate the PR into the py file?

That's the process I explained in the comment here: https://github.com/NanoComp/meep/pull/695#issuecomment-460254873

Instructions on checking out a local copy of a PR are here: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by JohnWeiner** [comment]
OK…I’m beginning to get it.  Haven’t played with pull requests before, but the checking out of pull requests locally looks like something I should know.

John

**Comment by ChristopherHogan** [comment]
The Mac issue is due to the `matplotlib` package and the fix is twofold. 
1. Import meep before importing matplitlib
2. Set the default backend to TkAgg via the matplotlibrc file:
```sh
$ mkdir -p ~/.matplotlib
$ echo "backend: TkAgg" > ~/.matplotlib/matplotlibrc
```

**Comment by JohnWeiner** [comment]
I incorporated the changes you propose in mpb_data_analysis.py: to wit, 

import meep before matplotlib, 
$ mkdir -p ~/.matplotlib $ echo "backend: TkAgg" > ~/.matplotlib/matplotlibrc,

and 

def tri_rods():
     # Import the ModeSolver defined in the mpb_tri_rods.py example
     from mpb_tri_rods import ms as tr_ms
      efields = []

 # Band function to collect the efields
def get_efields(tr_ms, band):

 
 
def diamond():
     # Import the ModeSolver from the mpb_diamond.py example
     from mpb_diamond import ms as d_ms

      dpwr = []

 def get_dpwr(ms, band):

However the mpb_data_analysis.py script still does not run. I get this puzzling error when I execute python on the file:
$ python ./miniconda3//pkgs/pymeep-1.7.1.dev-py36_nomkl_25/info/test/python/examples/mpb_data_analysis.py
Traceback (most recent call last):
  File "./miniconda3//pkgs/pymeep-1.7.1.dev-py36_nomkl_25/info/test/python/examples/mpb_data_analysis.py", line 28, in <module>
    tr_ms.run_tm(mpb.output_at_kpoint(mp.Vector3(1 / -3, 1 / 3), mpb.fix_efield_phase,
NameError: name 'tr_ms' is not defined.

It is as if the subroutine,

def tri_rods():
     # Import the ModeSolver defined in the mpb_tri_rods.py example
     from mpb_tri_rods import ms as tr_ms
      efields = []

is not read or something.

**Comment by ChristopherHogan** [comment]
I'm not sure if this is just a cut-and-paste issue, but the `tri_rods` code you show has some indentation issues that would break things. Can you make sure the indentation is exactly the same as https://github.com/NanoComp/meep/blob/master/python/examples/mpb_data_analysis.py?

**Comment by ChristopherHogan** [comment]
Great!

**Pull request merged**
