### PR TITLE
FAQ on 2d structures with out-of-plane wavevector

### PR DESCRIPTION
**Pull request by oskooi**
- How do I model a 2d structure involving an out-of-plane wavevector?

### CODE REVIEW

**Comment by stevengj** [comment]
Would be nice to try a simple calculation to check that the "special kz" feature is still working.  Just send normal-incident light at a flat interface and compute the transmission, then vary kz and it should vary the angle and hence change the transmission according to the Fresnel equation.

**Comment by stevengj** [comment]
For the same kz value, turning on `special_kz` should give you the same results (up to discretization error), but should be significantly faster.

**Comment by oskooi** [comment]
The `special_kz` feature is indeed working correctly and producing *significant* speed up. This is demonstrated in the following test (outlined above) which computes the Fresnel reflection coefficient of a flat interface for an incident planewave with out-of-plane wavevector using a 2d cell with and without `special_kz=True`.

```py
import meep as mp
import math

resolution = 100  # pixels/μm                                                                   

dpml = 1.0
sx = 10+2*dpml
sy = 1
cell_size = mp.Vector3(sx,sy)
pml_layers = [mp.PML(dpml,direction=mp.X)]

fcen = 1.0 # source wavelength = 1 μm                                                           

# angle of incident planewave (CCW about Y axis); plane of incidence: XZ
theta_inc = math.radians(20)                  
k_point = mp.Vector3(z=math.sin(theta_inc)).scale(fcen)

sources = [mp.Source(mp.GaussianSource(fcen,fwidth=0.2*fcen),
                     component=mp.Ez,
                     center=mp.Vector3(-0.5*sx+dpml),
                     size=mp.Vector3(y=sy))]

sim = mp.Simulation(cell_size=cell_size,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=k_point,
                    resolution=resolution)

sim.special_kz=True

refl_fr = mp.FluxRegion(center=mp.Vector3(-0.25*sx),
                        size=mp.Vector3(y=sy))
refl = sim.add_flux(fcen,0,1,refl_fr)

sim.run(until_after_sources=mp.stop_when_fields_decayed(50,mp.Ez,mp.Vector3(),1e-9))

empty_flux = mp.get_fluxes(refl)
empty_data = sim.get_flux_data(refl)
sim.reset_meep()

n_block = 3.5
geometry = [mp.Block(material=mp.Medium(index=n_block),
                     size=mp.Vector3(0.5*sx,mp.inf,mp.inf),
                     center=mp.Vector3(0.25*sx))]

sim = mp.Simulation(cell_size=cell_size,
                    boundary_layers=pml_layers,
                    geometry=geometry,
                    sources=sources,
                    k_point=k_point,
                    resolution=resolution)

sim.special_kz=True

refl = sim.add_flux(fcen,0,1,refl_fr)
sim.load_minus_flux_data(refl,empty_data)

sim.run(until_after_sources=mp.stop_when_fields_decayed(50,mp.Ez,mp.Vector3(),1e-9))

refl_flux = mp.get_fluxes(refl)

n1 = 1
n2 = n_block

# compute angle of refracted planewave in medium n2                                             
# for incident planewave in medium n1 at angle theta_in                                         
theta_out = lambda theta_in: math.asin(n1*math.sin(theta_in)/n2)

# compute Fresnel reflectance for P-polarization in medium n2                                   
# for incident planewave in medium n1 at angle theta_in                                         
Rfresnel = lambda theta_in: math.fabs((n1*math.cos(theta_out(theta_in))-n2*math.cos(theta_in))/\
(n1*math.cos(theta_out(theta_in))+n2*math.cos(theta_in)))**2

Rmeep = -refl_flux[0]/empty_flux[0]
Rfres = Rfresnel(theta_inc)
err = ((Rmeep-Rfres)/Rfres)**2

if mp.am_master():
    print("refl:, {}, {}, {}".format(Rmeep,Rfres,err))
```

**without `special_kz=True`**
```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
time for choose_chunkdivision = 0.0004042 s
Working in 3D dimensions.
Computational cell is 12 x 1 x 0.01 with resolution 100
time for set_epsilon = 0.354018 s
-----------
Meep: using complex fields.
on time step 182 (time=0.91), 0.0220431 s/step
on time step 476 (time=2.38), 0.0136401 s/step
on time step 750 (time=3.75), 0.0146486 s/step
on time step 1028 (time=5.14), 0.0144333 s/step
......
......
......
refl:, 0.2845149341754876, 0.2866488313668128, 5.541746204278983e-05

Elapsed run time = 850.9733 s
```

**with `special_kz=True`**
```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
time for choose_chunkdivision = 0.000371203 s
Working in 2D dimensions.
Computational cell is 12 x 1 x 0 with resolution 100
time for set_epsilon = 0.136474 s
-----------
on time step 3478 (time=17.39), 0.0011503 s/step
on time step 6817 (time=34.085), 0.00119827 s/step
on time step 10323 (time=51.615), 0.00114118 s/step
on time step 13663 (time=68.315), 0.00119801 s/step
......
......
......
refl:, 0.28451403206084924, 0.2866488313668128, 5.54643279098957e-05

Elapsed run time = 75.4823 s
```

As expected, the use of `special_kz` produces a 2d simulation with real fields rather than a 3d simulation with complex fields. The results are identical (and agree with the analytic value) but the run with `special_kz` has a wall-clock time (and average second/step value) which is faster by more than a factor of `11`.

Additional results for `theta_inc = math.radians(31)` are similar.

**without `special_kz=True`**
```
refl:, 0.2520226797751515, 0.254121008095802, 6.818137345458504e-05

Elapsed run time = 855.0981 s
```

**with `special_kz=True`**
```
refl:, 0.25201689107909936, 0.254121008095802, 6.855807871141609e-05

Elapsed run time = 74.4529 s
```

Next step: add this example to the test suite and update the documentation.

**Comment by stevengj** [comment]
One option is to make `special_kz=True` the default once it is sufficiently tested, so that any 2d cell automatically uses it for any kz.

**Pull request merged**
