### PR TITLE
Remove duplicate vertices in `Prism` object

### LINKED ISSUE #1520: `Prism` objects with duplicated vertices cause a segfault
Defining a Meep prism object with repeated coordinates seems to cause a segfault. It may be more user-friendly to perform some input validation here and, instead, raise an exception. Consider the example below, where the first and last vertex are the same:

```
import meep as mp

geometry = [
    mp.Prism(
        vertices=[
            mp.Vector3(51.07817888570662, -41.40026050039933, 0.0),
            mp.Vector3(26.07817888570662, -41.400436735950734, 0.0),
            mp.Vector3(16.07817888570662, -51.40027726778226, 0.0),
            mp.Vector3(11.875133679754981, -51.400343290466935, 0.0),
            mp.Vector3(-48.92182111429338, -51.400343290466935, 0.0),
            mp.Vector3(-48.92182111429338, 48.599656709533065, 0.0),
            mp.Vector3(51.07817888570662, 48.599656709533065, 0.0),
            mp.Vector3(51.07817888570662, -41.40026050039933, 0.0),
        ],
        height=100,
        sidewall_angle=0,
        material=mp.Medium(index=3.5),
    ),
]

simulation = mp.Simulation(
    cell_size=mp.Vector3(100.0, 100.0, 0.0),
    geometry=geometry,
    resolution=0.02,
)

simulation.init_sim()
```

### PR DESCRIPTION
**Pull request by oskooi**
Closes #1520.

### CODE REVIEW

**Comment by ahoenselaar** [comment]
Wouldn't one want to only consider consecutive vertices?

**Comment by stevengj** [comment]
Also, shouldn't this happen in libctl in the low-level constructor?

**Comment by oskooi** [comment]
> Wouldn't one want to only consider consecutive vertices?

This is true in the case of a GDS file for which the shapes must be [weakly simple polygons](https://en.wikipedia.org/wiki/Simple_polygon#Weakly_simple_polygon). This means that the polygon has segments which can intersect but not cross. This also means that representing holes requires connecting their boundary to the boundary of the enclosing shape which can give rise to duplicate vertices that are not consecutive.

In the general definition of a prism which involves convexity, any duplicate vertex would need to be removed whether it is consecutive or not.

> Also, shouldn't this happen in libctl in the low-level constructor?

Sure, we can move this feature to libctl and then add a test in Meep.

**Comment by ianwilliamson** [comment]
> This is true in the case of a GDS file for which the shapes must be [weakly simple polygons](https://en.wikipedia.org/wiki/Simple_polygon#Weakly_simple_polygon). This means that the polygon has segments which can intersect but not cross. This also means that representing holes requires connecting their boundary to the boundary of the enclosing shape which can give rise to duplicate vertices that are not consecutive.
> 
> In the general definition of a prism which involves convexity, any duplicate vertex would need to be removed whether it is consecutive or not.

Does the issue described in #1520 actually extend to the case of having _any_ duplicated vertices? I only showed the segfault with the duplicated first / last vertex while having subpixel smoothing enabled. Though, I could also see how there would be issues with having consecutive vertices.

Support for GDS-style polygons in the prism strikes me as being particularly useful given #1501, but if you do want to move forward with this approach, I would suggest raising an error instead of silently removing vertices. This would be quite confusing for users.

**Comment by stevengj** [comment]
To me, a polygon with duplicate consecutive vertices seems like a well-defined limiting case, that seems like a polygon with one fewer vertex.  (e.g. the limit of a quadrilateral as a side length goes to zero should be a triangle, not an error)

**Comment by stevengj** [comment]
e.g. matlab `polyshape` automatically deletes duplicate and even co-linear vertices. https://www.mathworks.com/matlabcentral/answers/606836-why-does-the-polyshape-function-deletes-the-vertices-in-the-input-when-there-are-no-duplicated-poi … and it seems pretty common in geometry packages to support deleting consecutive duplicate vertices, even if they are only approximately equal.

**Pull request closed without merging**
