### PR TITLE
Fix adjoint gradient with conductivities

### LINKED ISSUE #1811: Incorrect gradients when materials contain conductivities
As described in #1788, the adjoint solver does not produce accurate gradients when materials contain conductivities (including artificial damping terms). This is why the following lines are commented out on `master`:

https://github.com/NanoComp/meep/blob/7019c11e8b870ac8859166dd66a7f1f8df2b7c71/src/meepgeom.cpp#L603-L606

(Note that even if these lines were active, the actual conductivities themselves still need to be interpolated, as described in our paper -- but that's not why the gradients were failing, as the artificial damping terms introduced in #1788 also fail.)

When calculating Aᵤ (the derivative of the system matrix w.r.t. the design parameters), do a finite difference, performed here:

https://github.com/NanoComp/meep/blob/7019c11e8b870ac8859166dd66a7f1f8df2b7c71/src/meepgeom.cpp#L2566-L2592

The code that evaluates ε(ω,u) is found here:

https://github.com/NanoComp/meep/blob/7019c11e8b870ac8859166dd66a7f1f8df2b7c71/src/meepgeom.cpp#L2506-L2533

What's interesting is gradients for dispersive materials without any global conductivities (e.g. LN in the material database) work just fine -- meaning at least part of the above code is working well...

[Here](https://gist.github.com/smartalecH/e2e84d5f5b806a52582ba9dabc841c4f) is a test script that can be used during debugging.

([Here](https://gist.github.com/smartalecH/6511bfa9a1b002e33ebddaf6d2d22c77) is another script that uses LN for the material grid and produces accurate gradients)

(cc @mochen4)

### PR DESCRIPTION
**Pull request by mochen4**
Replaces https://github.com/NanoComp/meep/pull/1823. Fixes #1811.

### CODE REVIEW

**Comment by stevengj** [comment]
Test failure?

**Comment by mochen4** [comment]
> Test failure?

The double precision tests past but single precision one failed. I am still looking at why.

**Comment by stevengj** [comment]
Maybe try changing `FD_DEFAULT` in `python/adjoint/utils.py` to see if it is the fault of the finite-difference dε/du.

**Comment by stevengj** [comment]
In discussion with @mochen4, it seems like simply increasing the runtime fixes the problem — there seems to be a problem with the `stop_when_dft_decayed` convergence criterion in single precision.

**Comment by mawc2019** [comment]
When I compile the current master branch with `--enable-single` and Python 3.7.3, the check at `test_damping` still fails as described in [#1821](https://github.com/NanoComp/meep/pull/1821#issuecomment-982959565). The finite-difference gradients change a lot between double precision and single precision. I increased `minimum_run_time` to `2000` in [forward_simulation_damping](https://github.com/NanoComp/meep/blob/master/python/tests/test_adjoint_solver.py#L294) and [adjoint_solver_damping](https://github.com/NanoComp/meep/blob/master/python/tests/test_adjoint_solver.py#L339), but the check still failed. A tweak following @smartalecH 's [suggestion](https://github.com/NanoComp/meep/pull/1821#issuecomment-983757992) is as follows, with which the check passes locally. Maybe this issue is negligible because the online check does not fail.

```
    def test_damping(self):
        print("*** TESTING CONDUCTIVITIES ***")

        for frequencies in [[1/1.58, fcen, 1/1.53]]:
            ## filter the design field
            filter_radius = 0.12
            p_filtered = mpa.conic_filter(
                np.reshape(p,(Nx,Ny)),filter_radius,design_region_size.x,design_region_size.y,design_region_resolution).flatten()
            dp_filtered = mpa.conic_filter(
                np.reshape(dp,(Nx,Ny)),filter_radius,design_region_size.x,design_region_size.y,design_region_resolution).flatten()
            
            ## compute gradient using adjoint solver
            adjsol_obj, adjsol_grad = adjoint_solver_damping(p_filtered, frequencies)

            ## compute unperturbed S12
            S12_unperturbed = forward_simulation_damping(p_filtered, frequencies)

            ## compare objective results
            print("S12 -- adjoint solver: {}, traditional simulation: {}".format(adjsol_obj,S12_unperturbed))
            self.assertClose(adjsol_obj,S12_unperturbed,epsilon=1e-6)

            ## compute perturbed S12
            S12_perturbed = forward_simulation_damping(p_filtered+dp_filtered, frequencies)

            ## compare gradients
            if adjsol_grad.ndim < 2:
                adjsol_grad = np.expand_dims(adjsol_grad,axis=1)
            adj_scale = (dp_filtered[None,:]@adjsol_grad).flatten()
            fd_grad = S12_perturbed-S12_unperturbed
            print("Directional derivative -- adjoint solver: {}, FD: {}".format(adj_scale,fd_grad))
            tol = 0.06 if mp.is_single_precision() else 0.03
            self.assertClose(adj_scale,fd_grad,epsilon=tol)
```

**Comment by mochen4** [comment]
``test_damping`` is only added after this PR, so certainly you wouldn't see the failure for commits before this one. But that test is only about the added features in this PR, so I don't think it is the reason why #1821 fails locally on your machine.

> Maybe this issue is negligible because the online check does not fail.

The CI test runs the single-precision case with python3.9. I tested the master branch locally under python3.9 in single-precision, and tests passed. So I think the issue is either something with the python version or something in your local machine.

@mawc2019

**Pull request merged**
