### PR TITLE
Add tutorial using perturbation theory on a ring resonator in Python (#805)

### LINKED ISSUE #805: perturbation-theory tutorial example
It might be nice to add a tutorial example to https://meep.readthedocs.io/en/latest/Subpixel_Smoothing/ showing how to get the derivative dω/dR via perturbation theory rather than by center-difference approximations.

Basically, you just do the [perturbation-theory surface integral](http://math.mit.edu/~stevenj/papers/JohnsonIb02.pdf) with `get_field` at N=2πR/resolution equally spaced points around the ring's inner and outer surfaces — the average (multiplied by 2πR) is a good approximation for the surface integral.

### PR DESCRIPTION
**Pull request by danielwboyce**
Fixes #805

### CODE REVIEW

**Comment by danielwboyce** [comment]
I added the markdown file and .py files for a tutorial using perturbation theory on a ring resonator. The main thing I'm not sure about is how the markdown file will render on the website; I wasn't able to get mkdocs to work properly

**Comment by oskooi** [comment]
some initial comments:

- there are numerous markdown formatting errors when rendered using mkdocs mainly related to the equations (note that Latex equations can be embedded directly within markdown, see e.g. [Basics/Differential/Radar Cross Section](https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/#differentialradar-cross-section))
- rather than creating a separate page for this tutorial, let's add it as a new section to the end of [Ring Resonator in Cylindrical Coordinates](https://meep.readthedocs.io/en/latest/Python_Tutorials/Ring_Resonator_in_Cylindrical_Coordinates/)
- combine the two separate files in python/examples for the E<sub>z</sub> and H<sub>z</sub> polarizations into one with the polarization specified as a command-line parameter using `argparse`
- combine the two separate figures showing the relative error of the two polarizations into one and add plot labels
- rename the subsection tiles from "The E<sub>z</sub> Case" and "The H<sub>z</sub> Case" to e.g. "Parallel Fields" and "Perpendicular Fields"
- cite the perturbation-theory equation as Eq. 30 on p. 19 of the Photonic Crystals book rather than the 2002 PRE paper
- edit the first comment of this PR to "Fixes #805" (this will [close that Issue after this PR has been merged](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords))

Finally, rather than plotting the relative error as a function of dR for a fixed resolution, can you try the [convergence test](https://github.com/NanoComp/meep/issues/805#issuecomment-562277164) which @stevengj suggested: starting with a *fixed* dR (e.g. < 0.1/resolution, one tenth of the pixel dimension), verify that dω/dR computed using the two different approaches produces results which are comparable and that the brute-force result converges to the perturbation-theory result with *second-order accuracy* for the parallel fields but not for the perpendicular fields as the resolution increases.

**Comment by danielwboyce** [comment]
I made all the bullet point changes, but doing the comparison of dω/dR found by perturbation theory to dω/dR found by a center difference (dω/dR ≈ [ω(R+ΔR)–ω(R)] / ΔR) gave some iffy results, shown here

ring_cyl_perturbation_theory dw_dR_error

**Comment by oskooi** [comment]
The following script computes dω/dR using perturbation theory from the fields of the *unperturbed* structure and compares with the finite-difference result via the *perturbed* structure. The radius  of the ring is perturbed by a fixed amount.  The ring width is constant.

```py
import meep as mp
import numpy as np
import argparse


def main(args):
    n = 3.4                 # index of waveguide                                                                                                                       
    r = 1
    w = 1                   # ring width                                                                                                                               
    a = r                   # inner radius of ring                                                                                                                     
    b = a + w               # outer radius of ring                                                                                                                     
    pad = 4                 # padding between waveguide and edge of PML                                                                                                

    dpml = 2                # thickness of PML                                                                                                                         
    pml_layers = [mp.PML(dpml)]

    resolution = args.res

    sr = b + pad + dpml            # radial size (cell is from 0 to sr)                                                                                                
    dimensions = mp.CYLINDRICAL    # coordinate system is (r,phi,z) instead of (x,y,z)                                                                                 
    cell = mp.Vector3(sr)

    geometry = [mp.Block(center=mp.Vector3(a + (w / 2)),
                         size=mp.Vector3(w, mp.inf, mp.inf),
                         material=mp.Medium(index=n))]

    # find resonant mode with high Q using Harminv and broadband source                                                                                                

    fcen = 0.15         # pulse center frequency                                                                                                                       
    df = 0.1            # pulse width (in frequency)                                                                                                                   

    m = 5

    sources = [mp.Source(mp.GaussianSource(fcen,fwidth=df),
                         component=mp.Ez,
                         center=mp.Vector3(r+0.1))]

    sim = mp.Simulation(cell_size=cell,
                        geometry=geometry,
                        boundary_layers=pml_layers,
                        resolution=resolution,
                        sources=sources,
                        dimensions=dimensions,
                        m=m)

    h = mp.Harminv(mp.Ez, mp.Vector3(r+0.1), fcen, df)
    sim.run(mp.after_sources(h),
            until_after_sources=100)

    frq_unperturbed = h.modes[0].freq

    sim.reset_meep()

    # unperturbed geometry with narrowband source centered at resonant frequency                                                                                       

    fcen = frq_unperturbed
    df = 0.05*fcen

    sources = [mp.Source(mp.GaussianSource(fcen,fwidth=df),
                         component=mp.Ez,
                         center=mp.Vector3(r+0.1))]

    sim = mp.Simulation(cell_size=cell,
			geometry=geometry,
                        boundary_layers=pml_layers,
                        resolution=resolution,
                        sources=sources,
                        dimensions=dimensions,
                        m=m)

    sim.run(until_after_sources=100)

    npts = 50
    angles = 2 * np.pi / npts * np.arange(npts)
    deps_inner = 1 - n**2
    deps_inv_inner = 1 - 1/(n**2)
    deps_outer = n**2 - 1
    deps_inv_outer = 1/(n**2) - 1
    eps_norm_avg = 2/(1+1/n**2)

    fields_inner = []
    fields_outer = []
    for angle in angles:
        point = mp.Vector3(a, angle)
        e_z_field = abs(sim.get_field_point(mp.Ez, point))**2
        e_p_field = abs(sim.get_field_point(mp.Ep, point))**2
        field = e_z_field + e_p_field
        field_integrand = deps_inner * field
        fields_inner.append(field_integrand)
        point = mp.Vector3(b, angle)
        e_z_field = abs(sim.get_field_point(mp.Ez, point))**2
        e_p_field = abs(sim.get_field_point(mp.Ep, point))**2
        field = e_z_field + e_p_field
        field_integrand = deps_outer * field
        fields_outer.append(field_integrand)

    numerator_surface_integral = np.sum(fields_outer)*2*np.pi*b/npts + np.sum(fields_inner)*2*np.pi*a/npts
    denominator_integral = sim.electric_energy_in_box(center=mp.Vector3(), size=mp.Vector3(2*sr))
    perturb_theory_dw_dR = -frq_unperturbed * numerator_surface_integral / (2 * denominator_integral)

    # perturbed geometry with narrowband source                                                                                                                        

    dr = 0.02

    sim.reset_meep()
    a = r + dr   # inner radius of ring                                                                                                                                
    b = a + w    # outer radius of ring                                                                                                                                

    sources = [mp.Source(mp.GaussianSource(fcen,fwidth=df),
                         component=mp.Ez,
                         center=mp.Vector3(r+dr+0.1))]

    geometry = [mp.Block(center=mp.Vector3(a + (w / 2)),
                         size=mp.Vector3(w, mp.inf, mp.inf),
                         material=mp.Medium(index=n))]

    sim = mp.Simulation(cell_size=cell,
                        geometry=geometry,
                        boundary_layers=pml_layers,
                        resolution=resolution,
                        sources=sources,
                        dimensions=dimensions,
                        m=m)

    h = mp.Harminv(mp.Ez, mp.Vector3(r+dr+0.1), fcen, df)
    sim.run(mp.after_sources(h),
            until_after_sources=100)

    frq_perturbed = h.modes[0].freq

    finite_diff_dw_dR = (frq_perturbed - frq_unperturbed) / dr

    print("dwdR:, {} (pert. theory), {} (finite diff.)".format(perturb_theory_dw_dR,brute_force_dw_dR))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-res', type=int, default=100, help='resolution (default: 100 pixels/um)')
    args = parser.parse_args()
    main(args)
```
The following are the results at a resolution of 100 and 200. 

**resolution = 100**
```
dwdR:, -0.0854469622600482 (pert. theory), -0.08475884084030577 (finite diff.)
```

**resolution = 200**
```
dwdR:, -0.08544607152066104 (pert. theory), -0.08475789618134638 (finite diff.)
```

It seems that for this value of dR, the results have converged to six decimals. The next step would be to e.g. halve dR and rerun the test.

(Note: `m=5` is chosen which yields a resonant mode at frequency 0.175783 with Q of ~2000. Changing `m` produces results with similar agreement which is another validation.)

**Comment by danielwboyce** [comment]
I realized I made some mistakes in my calculus, which I've fixed now. I've also run more tests on the relative error in dω/dR and the discretization error seems to converge at a much lower resolution in the perpendicular fields than in the parallel fields for a given dR. I'll post some of the better plots that have come out of my runs.

**Comment by danielwboyce** [comment]
ring_cyl_perturbation_theory dw_dR_error

ring_cyl_perturbation_theory dw_dR_error
ring_cyl_perturbation_theory dw_dR_error

**Comment by stevengj** [comment]
One way to look at convergence would be to do your center-difference calculation at an extremely high resolution (e.g. 1000), and call that the "exact" result, and then plot the difference between the perturbation theory and this "exact" result as a function of the resolution where the perturbation-theory is computed.

**Pull request closed without merging**
