### PR TITLE
Adjoint cleanup

### PR DESCRIPTION
**Pull request by ianwilliamson**
This PR bases off of #1586 to clean up the adjoint module code by:

- ~~Applying formatting to the Python code to make it more readable~~ (Moved to #1590)
- Fixing several small bugs (equality rather than assignment, duplicated return statements, etc.)
- Adding method signatures to the abstract `ObjectiveQuantity` class
- Removing some non-standard Python things like `return` statements at the end of `__init__` methods
- Correcting spelling errors
- Removing unused imports

In a subsequent PR I will propose a fix for #1585.

### CODE REVIEW

**Comment by stevengj** [comment]
Note that the whitespace changes will complicate rebasing and merging other pending changes to the Python code.  Is there something easier than the procedure suggested in https://github.com/NanoComp/meep/pull/662?

**Comment by ianwilliamson** [comment]
> (What Python formatting tool did you use?)

`yapf` - https://github.com/google/yapf

**Comment by stevengj** [comment]
It would be better to have a separate PR with just the `yapf` changes, both for ease of review and for ease of rebasing.

**Comment by ianwilliamson** [comment]
> It would be better to have a separate PR with just the `yapf` changes, both for ease of review and for ease of rebasing.

Done in #1590.

**Comment by ianwilliamson** [comment]
I think this PR is good to go. These changes are relatively minor code health related things that should (hopefully) be uncontroversial. Let me know if there is any additional feedback.

**Pull request merged**
